<?php

use GuzzleHttp\Client;

class TestCase extends \PHPUnit_Framework_TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        require __DIR__.'/../vendor/autoload.php';

        $this->app = new \Innovating\Application(realpath('../'));

        $this->client = new Client(['base_uri' => 'http://innovating.dev']);
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
